package ifneeded mklite 0.4 [list source [file join $dir mklite.tcl]]
package ifneeded ratcl 4 [list source [file join $dir ratcl.tcl]]
package ifneeded vfs::m2m 1.7 [list source [file join $dir m2mvfs.tcl]]
package ifneeded vfs::mkcl 1.5 [list source [file join $dir mkclvfs.tcl]]
package ifneeded vlerq 4 [list load [file join $dir libvlerq4[info shared]]]
