require 'rubygems'
require 'hoe'

EXT_SHLIB = "ext/vlerq.#{Config::CONFIG['DLEXT']}"
EXT_FILES = FileList[
  "ext/*.c",
  "ext/*.h",
  "ext/extconf.rb",
  "ext/Makefile",
] 

RURAL_VERS = $1 if /\bVERSION\s*=\s*'(\d\.\d\.\d+)'/ =~ IO.read('lib/rural.rb')

Hoe.new('rural', RURAL_VERS) do |p|
  p.description = p.paragraphs_of('README.txt', 2..3).join("\n\n")
  p.summary = p.description.split("\n")[0]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")

  p.author = 'Jean-Claude Wippler'
  p.email = 'jcw@equi4.com'
  p.url = 'http://www.vlerq.org/'

  p.spec_extras[:extensions] = 'ext/extconf.rb'
  p.clean_globs += ['ext/*.o', 'ext/Makefile', EXT_SHLIB]
end

desc "Compile the Vlerq extension"
task :compile_ext => ["ext/Makefile", EXT_SHLIB ]

file 'ext/Makefile' => 'ext/extconf.rb' do
  Dir.chdir('ext') do ruby 'extconf.rb', '--with-cflags=-DDEBUG' end
end

file EXT_SHLIB => EXT_FILES do
  Dir.chdir('ext') do sh 'make' end
end

desc "Install the Vlerq extension"
task :install_ext => :compile_ext do
  Dir.chdir('ext') do sh 'make install' end
end

task :audit => :compile_ext
task :test => :compile_ext

task :install => :install_ext
